CREATE USER AIRLINE_ADMIN IDENTIFIED BY AirlineAdmin123;
CREATE USER CUSTOMER IDENTIFIED BY AirlineAdmin123;
 
GRANT CONNECT,RESOURCE TO AIRLINE_ADMIN;
GRANT CONNECT TO CUSTOMER;

ALTER USER AIRLINE_ADMIN QUOTA UNLIMITED ON DATA;
ALTER USER CUSTOMER QUOTA 250M ON DATA;

-- GRANT PERMISSIONS TO AIRLINE ADMIN
GRANT ALL ON PASSENGER TO AIRLINE_ADMIN;
GRANT ALL ON STATUS TO AIRLINE_ADMIN;
GRANT ALL ON BOOKING TO AIRLINE_ADMIN; 
GRANT ALL ON PROMOTION TO AIRLINE_ADMIN; 
GRANT ALL ON FLIGHT_SCHEDULES TO AIRLINE_ADMIN; 
GRANT ALL ON FLIGHT_SEAT_AVAILABILITY TO AIRLINE_ADMIN; 
GRANT ALL ON SEAT_TYPE TO AIRLINE_ADMIN; 
GRANT ALL ON ROUTES TO AIRLINE_ADMIN; 
GRANT ALL ON AIRPORTS TO AIRLINE_ADMIN; 
GRANT ALL ON FLIGHT_TYPE TO AIRLINE_ADMIN; 
GRANT ALL ON CUSTOMER TO AIRLINE_ADMIN; 

-- GRANT PERMISSIONS TO CUSTOMER
GRANT SELECT, INSERT, UPDATE ON CUSTOMER TO CUSTOMER;
GRANT SELECT ON FLIGHT_SCHEDULES TO CUSTOMER;
GRANT SELECT ON PROMOTION TO CUSTOMER;
GRANT SELECT ON SEAT_TYPE TO CUSTOMER;
GRANT SELECT, INSERT, UPDATE ON PASSENGER TO CUSTOMER;
GRANT SELECT,INSERT ON BOOKING TO CUSTOMER;

--GRANT PERMISSIONS ON VIEWS TO AIRLINE ADMIN
GRANT SELECT ON FLIGHTSOPERATIONALTODAY TO AIRLINE_ADMIN;
GRANT SELECT ON FREQUENT_USERS TO AIRLINE_ADMIN;
GRANT SELECT ON PASSENGER_TRAFFIC_BY_DESTINATION_STATE TO AIRLINE_ADMIN;
GRANT SELECT ON PASSENGER_TRAFFIC_BY_SOURCE_STATE TO AIRLINE_ADMIN;
GRANT SELECT ON PASSENGER_TRAVELLING_TODAY TO AIRLINE_ADMIN;
GRANT SELECT ON PASSENGERS_TRAVELLING_PER_QUARTER TO AIRLINE_ADMIN;
GRANT SELECT ON PROMOTIONSVIEW TO AIRLINE_ADMIN;
GRANT SELECT ON SEATDISTRIBUTION TO AIRLINE_ADMIN;
GRANT SELECT ON TOP_ROUTES_THIS_MONTH TO AIRLINE_ADMIN;
GRANT SELECT ON TOP_ROUTES_THIS_YEAR TO AIRLINE_ADMIN;
GRANT SELECT ON TOP_ROUTES_TODAY TO AIRLINE_ADMIN;
GRANT SELECT ON TOPFLIGHTSOPERATIONALTODAY TO AIRLINE_ADMIN;
GRANT SELECT ON TOPROUTESWITHVACANTSEATS TO AIRLINE_ADMIN;

--GRANT PERMISSIONS ON VIEWS TO CUSTOMER
GRANT SELECT ON FLIGHTSOPERATIONALTODAY TO CUSTOMER;
GRANT SELECT ON PROMOTIONSVIEW TO CUSTOMER;
GRANT SELECT ON SEATDISTRIBUTION TO CUSTOMER;

COMMIT;