CREATE USER AIRLINE_ADMIN IDENTIFIED BY AirlineAdmin123;
CREATE USER CUSTOMER IDENTIFIED BY AirlineAdmin123;
 
GRANT CONNECT,RESOURCE TO AIRLINE_USER;
GRANT CONNECT TO CUSTOMER;

ALTER USER AIRLINE_ADMIN QUOTA UNLIMITED ON DATA;
ALTER USER CUSTOMER QUOTA 250M ON DATA;

COMMIT;