CREATE USER AIRLINE_ADMIN IDENTIFIED BY AirlineAdmin123;
CREATE USER CUSTOMER IDENTIFIED BY AirlineAdmin123;
 
GRANT CONNECT,RESOURCE TO AIRLINE_ADMIN;
GRANT CONNECT TO CUSTOMER;
GRANT CREATE VIEW TO AIRLINE_ADMIN;

ALTER USER AIRLINE_ADMIN QUOTA UNLIMITED ON DATA;
ALTER USER CUSTOMER QUOTA 250M ON DATA;

COMMIT;