
-- Table Cusotmer
--------------------------------------------------------------------

CREATE TABLE CUSTOMER (
  CustomerID NUMBER NOT NULL,
  FirstName VARCHAR2(45) NOT NULL,
  LastName VARCHAR2(45) NOT NULL,
  Email VARCHAR2(45) NOT NULL,
  MobileNo VARCHAR2(45) NOT NULL,
  PRIMARY KEY (CustomerID));



-- Table FLIGHT_TYPE
--------------------------------------------------------------------

CREATE TABLE FLIGHT_TYPE (
  FlightTypeID NUMBER NOT NULL,
  FlightName VARCHAR2(45) NOT NULL,
  TotalNoOfSeats NUMBER NULL,
  PRIMARY KEY (FlightTypeID));



-- Table Airports
--------------------------------------------------------------------
CREATE TABLE AIRPORTS (
  Airports_ID NUMBER NOT NULL,
  State VARCHAR2(45) NULL,
  City VARCHAR2(45) NULL,
  Airport_Code VARCHAR2(45) NOT NULL UNIQUE,
  Airport_LongName VARCHAR2(100) NOT NULL UNIQUE,
  PRIMARY KEY (Airports_ID));


  -- Inserting values into the Customer table

INSERT INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, MOBILENO) 
VALUES (1, 'Fredrick', 'Kuhic', 'Fredrick97@gmail.com', '9851698275');
INSERT INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, MOBILENO) 
VALUES (2, 'Alexandra', 'Moen', 'Alexandra76@hotmail.com', '4111467271');
INSERT INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, MOBILENO) 
VALUES (3, 'Keith', 'Purdy', 'Keith.Purdy@gmail.com', '7086201608');
INSERT INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, MOBILENO) 
VALUES (4, 'Jerry', 'Hermann', 'Jerry46@hotmail.com', '5162354426');
INSERT INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, MOBILENO) 
VALUES (5, 'Jackie', 'Runte', 'Jackie.Runte@hotmail.com', '5165091524');
INSERT INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, MOBILENO) 
VALUES (6, 'Audrey', 'Kohler', 'Audrey_Kohler@yahoo.com', '1025161269');
INSERT INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, MOBILENO) 
VALUES (7, 'Maria', 'Rolfson', 'Maria_Rolfson91@gmail.com', '7339062790');
INSERT INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, MOBILENO) 
VALUES (8, 'Santiago', 'Rippin', 'Santiago.Rippin89@yahoo.com', '4155178945');
INSERT INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, MOBILENO) 
VALUES (9, 'Ruben', 'Okuneva', 'Ruben.Okuneva34@hotmail.com', '6849079568');
INSERT INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, MOBILENO) 
VALUES (10, 'Andrew', 'Leannon', 'Andrew_Leannon@gmail.com', '1308608494');
INSERT INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, MOBILENO) 
VALUES (11, 'Bob', 'Miller', 'Bob18@hotmail.com', '5947299265');
INSERT INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, MOBILENO) 
VALUES (12, 'Erma', 'Mills', 'Erma99@hotmail.com', '3205588765');
INSERT INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, MOBILENO) 
VALUES (13, 'Teresa', 'Kling', 'Teresa.Kling45@hotmail.com', '8329288895');
INSERT INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, MOBILENO) 
VALUES (14, 'Shannon', 'Turcotte', 'Shannon23@yahoo.com', '3606292461');
INSERT INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, MOBILENO) 
VALUES (15, 'Beulah', 'Cruickshank', 'Beulah6@hotmail.com', '1450149332');
INSERT INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, MOBILENO) 
VALUES (16, 'Darla', 'Balistreri', 'Darla.Balistreri25@gmail.com', '9077051489');
INSERT INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, MOBILENO) 
VALUES (17, 'Bradford', 'Stiedemann', 'Bradford39@gmail.com', '7668861386');
INSERT INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, MOBILENO) 
VALUES (18, 'Karen', 'Wintheiser', 'Karen_Wintheiser91@gmail.com', '9679794329');
INSERT INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, MOBILENO) 
VALUES (19, 'Gilberto', 'Pfeffer', 'Gilberto.Pfeffer@gmail.com', '2531343269');
INSERT INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, MOBILENO) 
VALUES (20, 'Angie', 'Hessel', 'Angie54@hotmail.com', '3300355373');
INSERT INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, MOBILENO) 
VALUES (21, 'Anne', 'Schroeder', 'Anne78@hotmail.com', '6147301761');
INSERT INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, MOBILENO) 
VALUES (22, 'Jacob', 'Bosco', 'Jacob_Bosco82@yahoo.com', '1243021907');
INSERT INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, MOBILENO) 
VALUES (23, 'Shelia', 'Koepp', 'Shelia74@gmail.com', '3150575514');
INSERT INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, MOBILENO) 
VALUES (24, 'Genevieve', 'Parker', 'Genevieve_Parker@yahoo.com', '8900435771');
INSERT INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, MOBILENO) 
VALUES (25, 'Carroll', 'Murphy', 'Carroll_Murphy62@gmail.com', '7636236121');


-- Inserting values into Flight_Type table
INSERT INTO FLIGHT_TYPE (FLIGHTTYPEID, FLIGHTNAME, TOTALNOOFSEATS) 
VALUES (1, 'A220', 75);
INSERT INTO FLIGHT_TYPE (FLIGHTTYPEID, FLIGHTNAME, TOTALNOOFSEATS) 
VALUES (2, 'A320', 100);
